-- Update Creative Agency Portfolio (id: 23d8678a-0709-4133-951d-60b948a7decd) and Fitness Studio Pro (id: c96e31fa-825b-4f06-a636-949e9d4724fe)
UPDATE templates 
SET preview_data = $BODY$[
  {"type": "navigation", "logo": "Pixel Perfect Studios", "items": [{"label": "Home", "href": "#home"}, {"label": "Portfolio", "href": "#portfolio"}, {"label": "Services", "href": "#services"}, {"label": "About", "href": "#about"}, {"label": "Contact", "href": "#contact"}]},
  {"type": "hero", "heading": "Where Creativity Meets Innovation", "subheading": "Award-winning design and branding for forward-thinking brands", "content": "We craft memorable digital experiences that captivate audiences and drive meaningful engagement. From concept to execution, we bring your vision to life.", "backgroundImage": "https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1920&q=80", "primaryButton": {"text": "View Our Work", "href": "#portfolio"}, "secondaryButton": {"text": "Start a Project", "href": "#contact"}},
  {"type": "about", "heading": "Crafting Digital Excellence Since 2012", "subheading": "A Creative Force Behind 500+ Successful Brands", "content": "We are a full-service creative agency passionate about transforming ideas into stunning visual narratives. Our multidisciplinary team combines artistic vision with strategic thinking to deliver work that not only looks beautiful but drives business results.", "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80"},
  {"type": "stats", "heading": "Our Creative Impact", "items": [{"value": "500+", "label": "Projects Delivered"}, {"value": "120+", "label": "Happy Clients"}, {"value": "25", "label": "Design Awards"}, {"value": "12", "label": "Team Members"}]},
  {"type": "services", "heading": "What We Do Best", "subheading": "Comprehensive creative services for modern brands", "items": [{"icon": "Palette", "title": "Brand Identity", "description": "Create distinctive brand identities that resonate with your target audience and stand out in the market."}, {"icon": "Monitor", "title": "Web Design & Development", "description": "Design and build beautiful, responsive websites that deliver exceptional user experiences."}, {"icon": "Camera", "title": "Photography & Video", "description": "Capture stunning visuals that tell your story and connect emotionally with your audience."}, {"icon": "Zap", "title": "Motion Graphics", "description": "Bring your ideas to life with engaging animations and dynamic visual content."}, {"icon": "Layout", "title": "UI/UX Design", "description": "Design intuitive interfaces focused on user needs and business objectives."}, {"icon": "TrendingUp", "title": "Digital Marketing", "description": "Develop and execute creative campaigns that drive engagement and conversions."}]},
  {"type": "projects", "heading": "Featured Work", "subheading": "A showcase of our most impactful projects", "items": [{"title": "Urban Harvest - Organic Food Brand", "description": "Complete rebrand including logo design, packaging, and digital presence for a sustainable food company", "image": "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80", "tags": ["Branding", "Packaging", "Web Design"]}, {"title": "TechFlow - SaaS Platform", "description": "Modern web application design with focus on user experience and conversion optimization", "image": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80", "tags": ["UI/UX", "Web App", "SaaS"]}, {"title": "Luxe Living - Interior Design", "description": "Elegant brand identity and photography showcasing high-end interior design services", "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80", "tags": ["Branding", "Photography", "Luxury"]}, {"title": "FitForward - Fitness App", "description": "Mobile app design and motion graphics for an innovative fitness tracking platform", "image": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80", "tags": ["Mobile App", "Motion Design", "Fitness"]}, {"title": "GreenTech Solutions", "description": "Corporate identity and marketing campaign for a sustainable energy company", "image": "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=600&q=80", "tags": ["Corporate", "Sustainability", "Campaign"]}, {"title": "Artisan Coffee Co.", "description": "Brand strategy, packaging design, and social media content for specialty coffee roaster", "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=600&q=80", "tags": ["F&B", "Packaging", "Social Media"]}]},
  {"type": "testimonials", "heading": "Client Love", "items": [{"quote": "The team at Pixel Perfect transformed our brand completely. Their creative vision and attention to detail exceeded all expectations.", "author": "Emma Williams", "role": "Marketing Director, Urban Harvest", "image": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=200&q=80"}, {"quote": "Working with them was a game-changer. They understood our vision and brought it to life in ways we hadn''t imagined.", "author": "Alex Chen", "role": "Founder, TechFlow", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80"}, {"quote": "Incredible talent and professionalism. They delivered on time, on budget, and beyond our wildest expectations.", "author": "Sofia Martinez", "role": "CEO, Luxe Living", "image": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80"}]},
  {"type": "cta", "heading": "Ready to Create Something Amazing?", "content": "Let''s collaborate on your next project and bring your creative vision to life. Schedule a free consultation to get started.", "buttons": [{"text": "Start Your Project", "variant": "secondary", "href": "#contact"}]},
  {"type": "form", "heading": "Let''s Talk", "subheading": "Tell us about your project and we will get back to you within 24 hours", "fields": [{"name": "name", "type": "text", "label": "Your Name", "required": true}, {"name": "email", "type": "email", "label": "Email Address", "required": true}, {"name": "company", "type": "text", "label": "Company Name", "required": false}, {"name": "budget", "type": "text", "label": "Project Budget", "required": false}, {"name": "message", "type": "textarea", "label": "Tell us about your project", "required": true}]}
]$BODY$::jsonb
WHERE id = '23d8678a-0709-4133-951d-60b948a7decd';

UPDATE templates 
SET preview_data = $BODY$[
  {"type": "navigation", "logo": "PowerFit Elite", "items": [{"label": "Home", "href": "#home"}, {"label": "Classes", "href": "#classes"}, {"label": "Trainers", "href": "#trainers"}, {"label": "Pricing", "href": "#pricing"}, {"label": "Join Now", "href": "#contact"}]},
  {"type": "hero", "heading": "Transform Your Body, Transform Your Life", "subheading": "Elite training programs designed to help you achieve your fitness goals", "content": "Join our community of dedicated athletes and fitness enthusiasts. Whether you are starting your fitness journey or pushing to the next level, we have the perfect program for you.", "backgroundImage": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1920&q=80", "primaryButton": {"text": "Start Free Trial", "href": "#contact"}, "secondaryButton": {"text": "View Classes", "href": "#classes"}},
  {"type": "about", "heading": "More Than Just a Gym", "subheading": "Your Complete Fitness Destination Since 2015", "content": "PowerFit Elite is a premium fitness facility offering state-of-the-art equipment, expert trainers, and a supportive community. We combine cutting-edge training methods with personalized coaching to help you reach your goals faster and safer.", "image": "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=800&q=80"},
  {"type": "stats", "heading": "Our Fitness Family", "items": [{"value": "2,500+", "label": "Active Members"}, {"value": "50+", "label": "Weekly Classes"}, {"value": "20", "label": "Expert Trainers"}, {"value": "97%", "label": "Member Satisfaction"}]},
  {"type": "services", "heading": "Training Programs", "subheading": "Diverse programs to match your fitness level and goals", "items": [{"icon": "Zap", "title": "HIIT Training", "description": "High-intensity interval training for maximum calorie burn and cardiovascular fitness."}, {"icon": "Dumbbell", "title": "Strength Training", "description": "Build muscle and increase strength with our comprehensive weight training programs."}, {"icon": "Heart", "title": "Personal Training", "description": "One-on-one coaching tailored to your specific goals and fitness level."}, {"icon": "Users", "title": "Group Classes", "description": "Energizing group workouts including yoga, spin, boxing, and more."}, {"icon": "Activity", "title": "Functional Fitness", "description": "Improve everyday movement patterns and overall physical performance."}, {"icon": "Award", "title": "Nutrition Coaching", "description": "Expert guidance on meal planning and nutrition to fuel your fitness journey."}]},
  {"type": "projects", "heading": "Member Success Stories", "subheading": "Real transformations from real people", "items": [{"title": "Jessica - Lost 50 Pounds", "description": "6 months of dedication led to an amazing transformation and newfound confidence", "image": "https://images.unsplash.com/photo-1518310952931-b1de897abd40?auto=format&fit=crop&w=600&q=80", "tags": ["Weight Loss", "Transformation", "6 Months"]}, {"title": "Marcus - Marathon Ready", "description": "From couch to completing his first marathon in under a year", "image": "https://images.unsplash.com/photo-1552196563-55cd4e45efb3?auto=format&fit=crop&w=600&q=80", "tags": ["Endurance", "Running", "Achievement"]}, {"title": "Linda - Strength Gains", "description": "Increased strength by 200% and competed in her first powerlifting meet", "image": "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80", "tags": ["Strength", "Powerlifting", "Competition"]}]},
  {"type": "testimonials", "heading": "What Our Members Say", "items": [{"quote": "Best gym I''ve ever joined! The trainers are knowledgeable, the facilities are spotless, and the community is incredibly supportive.", "author": "Mike Johnson", "role": "Member since 2021", "image": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80"}, {"quote": "I''ve achieved fitness goals I never thought possible. The personalized attention and variety of classes keep me motivated every day.", "author": "Rachel Green", "role": "Member since 2020", "image": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80"}, {"quote": "The trainers here truly care about your success. They pushed me to be my best while keeping workouts fun and challenging.", "author": "Chris Anderson", "role": "Member since 2019", "image": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80"}]},
  {"type": "cta", "heading": "Start Your Fitness Journey Today", "content": "Get a free 7-day trial membership and experience everything PowerFit Elite has to offer. No commitment required.", "buttons": [{"text": "Claim Your Free Trial", "variant": "secondary", "href": "#contact"}]},
  {"type": "form", "heading": "Join PowerFit Elite", "subheading": "Fill out the form to get started with your free trial", "fields": [{"name": "name", "type": "text", "label": "Full Name", "required": true}, {"name": "email", "type": "email", "label": "Email Address", "required": true}, {"name": "phone", "type": "tel", "label": "Phone Number", "required": true}, {"name": "goals", "type": "textarea", "label": "What are your fitness goals?", "required": false}]}
]$BODY$::jsonb
WHERE id = 'c96e31fa-825b-4f06-a636-949e9d4724fe';