-- Update Consulting Firm Classic template (id: 492f850b-a02d-46ac-aeb0-7b3820fe69bf)
UPDATE templates 
SET preview_data = $BODY$[
  {"type": "navigation", "logo": "Strategic Consulting Partners", "items": [{"label": "Home", "href": "#home"}, {"label": "Services", "href": "#services"}, {"label": "Industries", "href": "#industries"}, {"label": "Case Studies", "href": "#cases"}, {"label": "Contact", "href": "#contact"}]},
  {"type": "hero", "heading": "Strategic Solutions for Complex Challenges", "subheading": "World-class consulting services that drive measurable results", "content": "Partner with industry-leading consultants who bring deep expertise, proven methodologies, and innovative thinking to solve your most critical business challenges.", "backgroundImage": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1920&q=80", "primaryButton": {"text": "Schedule Consultation", "href": "#contact"}, "secondaryButton": {"text": "Our Expertise", "href": "#services"}},
  {"type": "about", "heading": "Excellence in Consulting Since 2005", "subheading": "Trusted Advisors to Fortune 500 and High-Growth Companies", "content": "With over 18 years of experience across multiple industries, we combine strategic insight with practical execution. Our consultants have worked with leading organizations to drive transformational change, optimize operations, and unlock new growth opportunities.", "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80"},
  {"type": "stats", "heading": "Proven Track Record", "items": [{"value": "200+", "label": "Projects Completed"}, {"value": "$2B+", "label": "Value Created"}, {"value": "25", "label": "Industries Served"}, {"value": "98%", "label": "Client Retention"}]},
  {"type": "services", "heading": "Comprehensive Consulting Services", "subheading": "End-to-end solutions tailored to your unique challenges", "items": [{"icon": "Target", "title": "Strategy & Planning", "description": "Define winning strategies and roadmaps for sustainable competitive advantage."}, {"icon": "TrendingUp", "title": "Digital Transformation", "description": "Accelerate innovation and modernize operations with cutting-edge technology."}, {"icon": "Users", "title": "Organizational Design", "description": "Build high-performing organizations aligned with your strategic objectives."}, {"icon": "Zap", "title": "Operations Excellence", "description": "Streamline processes and drive efficiency across your value chain."}, {"icon": "Shield", "title": "Risk & Compliance", "description": "Navigate regulatory requirements and mitigate business risks effectively."}, {"icon": "BarChart", "title": "M&A Advisory", "description": "Expert guidance through mergers, acquisitions, and strategic partnerships."}]},
  {"type": "projects", "heading": "Featured Case Studies", "subheading": "Real results for real businesses", "items": [{"title": "Global Retail Transformation", "description": "Helped Fortune 500 retailer achieve $500M cost savings through supply chain optimization", "image": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80", "tags": ["Retail", "Operations", "Cost Reduction"]}, {"title": "FinTech Digital Strategy", "description": "Enabled rapid market entry with comprehensive go-to-market strategy and execution", "image": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80", "tags": ["Financial Services", "Strategy", "Growth"]}, {"title": "Healthcare System Redesign", "description": "Improved patient outcomes by 40% through integrated care model implementation", "image": "https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=600&q=80", "tags": ["Healthcare", "Operations", "Innovation"]}]},
  {"type": "testimonials", "heading": "What Our Clients Say", "items": [{"quote": "Their strategic insights and hands-on approach delivered results beyond our expectations. True partners in every sense.", "author": "David Martinez", "role": "CFO, Global Manufacturing Corp", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80"}, {"quote": "The transformation they led has positioned us for sustained growth in an increasingly competitive market.", "author": "Lisa Thompson", "role": "CEO, TechHealth Solutions", "image": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80"}, {"quote": "Outstanding expertise combined with practical, executable recommendations. The value has been immense.", "author": "James Wilson", "role": "VP Strategy, Financial Services Inc", "image": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80"}]},
  {"type": "cta", "heading": "Let''s Solve Your Biggest Challenges", "content": "Connect with our consulting experts to explore how we can help you achieve breakthrough results.", "buttons": [{"text": "Contact Our Team", "variant": "secondary", "href": "#contact"}]},
  {"type": "form", "heading": "Start the Conversation", "subheading": "We will respond within one business day", "fields": [{"name": "name", "type": "text", "label": "Full Name", "required": true}, {"name": "email", "type": "email", "label": "Work Email", "required": true}, {"name": "company", "type": "text", "label": "Company", "required": true}, {"name": "title", "type": "text", "label": "Job Title", "required": false}, {"name": "message", "type": "textarea", "label": "How can we help?", "required": true}]}
]$BODY$::jsonb
WHERE id = '492f850b-a02d-46ac-aeb0-7b3820fe69bf';